Dashboard/Dashboard/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^mess/', include('mess.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^terashare/', include('terashare.urls')),
    url(r'', include('profiles.urls')),
    url(r'^timetable/', include('timetable.urls')),
    url(r'^parcel/', include('parcels.urls')),
    url(r'^shuttle/', include('shuttleservice.urls')),
    url(r'^welfare/', include('welfare.urls')),
    url(r'^rooms/', include('rooms.urls')),
    url(r'^', include('home.urls')),
    url(r'^lostfound/',include('lostfound.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Dashboard/home/urls.py
from django.conf.urls import url
from . import views

app_name = 'home'

urlpatterns = [
    url(r'^$', views.Home, name='home')
]

Dashboard/lostfound/urls.py
from django.conf.urls import url
from django.contrib import admin
from . import views

app_name='lostfound'

urlpatterns=[
    url(r'^$',views.HomeView,name='homelost'),
    url(r'^reportlost$',views.LostView,name='reportlost'),
    url(r'^reportfound$',views.FoundView,name='reportfound'),
    url(r'^matchfound$',views.CompareView,name='matchfound'),
 ]

Dashboard/parcels/urls.py
from django.conf.urls import url
from . import views

app_name = 'parcel'


urlpatterns = [
    url(r'^$', views.homepage, name='parcels')
]

Dashboard/profiles/urls.py
from django.conf.urls import url
from . import views

app_name = 'profiles'

urlpatterns = [
    url(r'^register/$', views.register, name='register'),
    url(r'^login', views.login_user, name='login_user'),
    url(r'^logout', views.logout_user, name='logout_user'),
    url(r'^home', views.home, name='home')
]

Dashboard/rooms/urls.py
from django.conf.urls import url
from django.contrib import admin
from . import views

app_name='rooms'

urlpatterns=[
    url(r'^$',views.HomeView,name='home'),
    url(r'^requestroom$',views.RequestView,name='requestroom'),
    url(r'^viewrequest$',views.ShowView,name='showrequest'),
    url(r'^detail$', views.DetailView, name='detail'),


  ]

Dashboard/welfare/urls.py
from django.conf.urls import url
from . import views

app_name = 'welfare'

urlpatterns = [
    url(r'^home/$', views.Home, name='home'),
    url(r'^complain/$', views.complaint, name='register'),
    url(r'^complaints/$', views.complaints, name='complaints')
]

Dashboard/home/models.py
from django.db import models

# Create your models here.

Dashboard/rooms/models.py
from django.db import models

# Create your models here.
class AccomodationForm(models.Model):
    genders = (('Male', 'Male'), ('Female', 'Female'))
    Name1 = models.CharField(max_length=100)
    Gender1 = models.CharField(max_length=10, choices=genders)
    Name2 = models.CharField(max_length=100)
    Gender2 = models.CharField(max_length=10, choices=genders)
    Name3 = models.CharField(max_length=100)
    Gender3 = models.CharField(max_length=10, choices=genders)
    Purpose=models.CharField(max_length=500)

    def __str__(self):
        return self.Name1

Dashboard/rooms/forms.py
from django import forms
from .models import AccomodationForm
from django.forms import ModelForm


class RequestForm(ModelForm):

    class Meta:
        model = AccomodationForm
        fields = ['Name1','Gender1','Name2','Gender2','Name3','Gender3','Purpose']

Dashboard/home/views.py
from django.shortcuts import render

# Create your views here.
def Home(request):
    if not request.user.is_authenticated():
        return render(request, 'profiles/home.html')
    else:
        return render(request, 'home/home.html')

Dashboard/rooms/views.py
from django.shortcuts import render
from .models import AccomodationForm
from .forms import RequestForm
from django.shortcuts import redirect
from django.contrib import messages

def HomeView(request):
    if not request.user.is_authenticated():
        return render(request, 'profiles/login.html')
    else:
        return render(request,'rooms/home.html')

def ShowView(request):
    if not request.user.is_authenticated():
        return render(request, 'profiles/login.html')
    else:
        object_list = AccomodationForm.objects.all()
        context={"object_list":object_list}
        return render(request, 'rooms/viewrequest.html', context)

def DetailView(request):
    if not request.user.is_authenticated():
        return render(request, 'profiles/login.html')
    else:
        return render(request,'rooms/detail.html')

def RequestView(request):
    if not request.user.is_authenticated():
        return render(request, 'profiles/login.html')
    else:
        form = RequestForm(request.POST or None, request.FILES or None)
        if request.method == 'POST':
            if form.is_valid():
                form.save()
                messages.success(request, "Your Room Booking is Done!! ")
                return redirect('rooms:home')
            else:
                messages.error(request, "The Request was not Registered, Please Try Again")
        context = {"form":form}
        return render(request, 'rooms/requestroom.html', context)

Dashboard/templates/rooms/base.html
<!DOCTYPE html>
  <html>
    <head>
        <title>{% block title %}Terashare{% endblock %}</title>
		<link href='https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css' rel='stylesheet'
			type='text/css'>
      <!--Import Google Icon Font-->
      <link href="http://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
      <!--Import materialize.css-->
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.98.0/css/materialize.min.css"  media="screen,projection"/>

      <!--Let browser know website is optimized for mobile-->
      <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    {% block css %} {% endblock %}
    </head>

    <body>
		<nav>
			<div class="nav-wrapper indigo darken-3">
			  <ul class="brand-logo left" id="gnius">GNius</ul>
			  <a href="" data-activates="mobile-demo" class="button-collapse right"><i class="material-icons">menu</i></a>

			  <ul class="brand-logo center hide-on-med-and-down">
				<li><a  href="{% url 'home:home' %}">Home</a></li>
				<li><a href="{% url 'terashare:home' %}">TeraShare</a></li>
				<li><a href="{% url 'timetable:table' %}">Time Table</a></li>
                  <li><a href="{% url 'welfare:home' %}">Welfare</a></li>
                  <li><a href="{% url 'parcel:parcels' %}" >Parcel</a></li>
                  <li><a href="{% url 'shuttleservice:buses' %}">Shuttle</a></li>
                  <li><a  class="active" href="{% url 'rooms:home' %}">Rooms</a></li>
                  <li><a href="{% url 'lostfound:homelost' %}">Lost/Found</a></li>
			  </ul>

				<ul class="brand-logo right hide-on-med-and-down">
				 <li><a href="{% url 'profiles:logout_user' %}"><i class="material-icons">exit_to_app</i></a></li>
				<li><a href="#" data-letters="{{ request.user.username|upper|make_list|first }}" class="letters"></a></li>
			  </ul>

			<ul class="side-nav right indigo darken-3" id="mobile-demo">
				<li><a href="{% url 'home:home' %}">Home</a></li>
				<li><a href="{% url 'terashare:home' %}">TeraShare</a></li>Z
				<li><a href="{% url 'timetable:table' %}">Time Table</a></li>
                <li><a href="{% url 'welfare:home' %}">Welfare</a></li>
                <li><a href="{% url 'parcel:parcels' %}" >Parcel</a></li>
                <li><a href="{% url 'shuttleservice:buses' %}">Shuttle</a></li>
                 <li><a  class="active" href="{% url 'rooms:home' %}">Rooms</a></li>
                  <li><a href="{% url 'lostfound:homelost' %}">Lost/Found</a></li>
				 <li><a href="{% url 'profiles:logout_user' %}"><i class="material-icons">exit_to_app</i></a></li>
				<li><a href="#" data-letters="{{ request.user.username|upper|make_list|first }}" class="letters"></a></li></ul>

			</div>
  		</nav>
  		<div class="section indigo darken-1 center" style="color: #ffffff; padding: 20px;">
  			{% block titl %}Hello! {{ request.user.username }}{% endblock %}
  		</div>
		<script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.98.0/js/materialize.min.js"></script>
		<script>
			 $(".button-collapse").sideNav({edge: 'right'});
		</script>

    {% block body %}

    {% endblock %}
	  </body>
</html>

Dashboard/templates/rooms/detail.html
Details to be added

Dashboard/templates/rooms/home.html
{% extends 'rooms/base.html' %}
{% block css %}
{% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'rooms/home.css' %}">
{% endblock %}
{% block title %}
    Rooms
{% endblock %}
{% block titl %}
    Book a room for your guests
{% endblock %}
{% block body %}
    <div class="container">
	  		<div class="row">
	  			<div class="container">
	  				<div class="row contents-box center">
                         <h4>Some Days with your Beloved Ones:</h4>
            <h6>But we follow a strict pathway. <br> Request a Room to the Concerned</h6>
            <div class="col s12 center"><a href="{% url 'rooms:requestroom' %}"><button class="upload-btn">Room Request</button></a></div>
</div>
				</div>
			</div>
</div>
{% endblock %}

Dashboard/templates/rooms/messages.html
{% if messages %}
	<div class = 'messages'></div>
	    {% for message in messages%}
	    	<h2>{{message}}</h2></br>
	    {% endfor %}
    </div>
{% endif %}

Dashboard/templates/rooms/requestroom.html
{% extends 'rooms/base.html' %}
{% block css %}
{% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'rooms/req.css' %}">
{% endblock %}
{% block titl %}
    Request a room
{% endblock %}
{% block body %}

  		<div class="container">
	  		<div class="row">
	  			<div class="container">
	  				<div class="row">
						<div class="form-box center">
						<form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
							{% csrf_token %}
                            {% for field in form %}
                                <div class="non input-field left" style="color: #ffffff">
								{{ field.label }}
                                    </div>
                                <div class="input-field">
                                <div class="input-field">
                                    {{ field }}
                                </div>
                                </div>
                            {% endfor %}
							<div class="input-field">
							<input class="center" type="submit" name="submit_btn" value="Submit">
							</div><br>
                            <div class="left"><a href="{% url 'rooms:home' %}"><i class="material-icons" style="color: white;">arrow_backward</i></a></div>
                            <div class="right"><a href="{% url 'rooms:showrequest' %}"><i class="material-icons" style="color: white;">arrow_forward</i></a></div>


						</form>

						</div>

					</div>
				</div>
			</div>
		</div>
    <script>
    $('select').material_select();
    $('')
    </script>
    <script>
    $('.datepicker').pickadate({
    selectMonths: true, // Creates a dropdown to control month
    selectYears: 15 // Creates a dropdown of 15 years to control year
  });
    </script>
{% endblock %}

Dashboard/templates/rooms/viewrequest.html
{% extends 'rooms/base.html' %}
{% block css %}
{% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'rooms/viewr.css' %}">
{% endblock %}
{% block titl %}
    your requests
{% endblock %}
{% block body %}
<div class="container">
	<div class="row">
		<div class="container">
			<div class="row contents-box">
                <u1>

                    {%for object in object_list %}
                        <li>{{ object.Datefrom }} - {{ object.Dateto }} </li>
                    {%  endfor %}
                 </u1>
			</div>
		</div>
	</div>
</div>
{% endblock %}


