Dashboard/Dashboard/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^mess/', include('mess.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^terashare/', include('terashare.urls')),
    url(r'', include('profiles.urls')),
    url(r'^timetable/', include('timetable.urls')),
    url(r'^parcel/', include('parcels.urls')),
    url(r'^shuttle/', include('shuttleservice.urls')),
    url(r'^welfare/', include('welfare.urls')),
    url(r'^rooms/', include('rooms.urls')),
    url(r'^', include('home.urls')),
    url(r'^lostfound/',include('lostfound.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Dashboard/home/urls.py
from django.conf.urls import url
from . import views

app_name = 'home'

urlpatterns = [
    url(r'^$', views.Home, name='home')
]

Dashboard/lostfound/urls.py
from django.conf.urls import url
from django.contrib import admin
from . import views

app_name='lostfound'

urlpatterns=[
    url(r'^$',views.HomeView,name='homelost'),
    url(r'^reportlost$',views.LostView,name='reportlost'),
    url(r'^reportfound$',views.FoundView,name='reportfound'),
    url(r'^matchfound$',views.CompareView,name='matchfound'),
 ]

Dashboard/parcels/urls.py
from django.conf.urls import url
from . import views

app_name = 'parcel'


urlpatterns = [
    url(r'^$', views.homepage, name='parcels')
]

Dashboard/profiles/urls.py
from django.conf.urls import url
from . import views

app_name = 'profiles'

urlpatterns = [
    url(r'^register/$', views.register, name='register'),
    url(r'^login', views.login_user, name='login_user'),
    url(r'^logout', views.logout_user, name='logout_user'),
    url(r'^home', views.home, name='home')
]

Dashboard/rooms/urls.py
from django.conf.urls import url
from django.contrib import admin
from . import views

app_name='rooms'

urlpatterns=[
    url(r'^$',views.HomeView,name='home'),
    url(r'^requestroom$',views.RequestView,name='requestroom'),
    url(r'^viewrequest$',views.ShowView,name='showrequest'),
    url(r'^detail$', views.DetailView, name='detail'),


  ]

Dashboard/welfare/urls.py
from django.conf.urls import url
from . import views

app_name = 'welfare'

urlpatterns = [
    url(r'^home/$', views.Home, name='home'),
    url(r'^complain/$', views.complaint, name='register'),
    url(r'^complaints/$', views.complaints, name='complaints')
]

Dashboard/home/models.py
from django.db import models

# Create your models here.

Dashboard/welfare/models.py
from django.contrib.auth.models import User
from django.db import models
class Category(models.Model):
    category = models.CharField(max_length=50)

    def __str__(self):
        return  self.category

class Complaint(models.Model):
    Title = models.CharField(max_length=99)
    Category = models.ForeignKey(Category, on_delete=models.CASCADE)
    Description = models.TextField(max_length=499)
    Hostel = models.CharField(max_length=25)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    updated = models.DateTimeField(auto_now=True, auto_now_add=False)
    timestamp = models.DateTimeField(auto_now=False, auto_now_add=True)
    is_resolved = models.BooleanField(default=False)

    def __str__(self):
        return self.Title

Dashboard/welfare/forms.py
from django import forms
from .models import Complaint

class ComplaintForm(forms.ModelForm):
    class Meta:
        model = Complaint
        fields = ['Category', 'Title', 'Description', 'Hostel']

Dashboard/home/views.py
from django.shortcuts import render

# Create your views here.
def Home(request):
    if not request.user.is_authenticated():
        return render(request, 'profiles/home.html')
    else:
        return render(request, 'home/home.html')

Dashboard/welfare/views.py
from django.shortcuts import render, get_object_or_404
from .forms import ComplaintForm
from .models import Category, Complaint

# Create your views here.
def Home(request):
    if not request.user.is_authenticated():
        return render(request, 'profiles/login.html')
    else:
        return render(request, 'welfare/home.html')


def complaint(request):
    if not request.user.is_authenticated():
        return render(request, 'profiles/login.html')
    else:
        form = ComplaintForm(request.POST or None)
        if form.is_valid():
            complaint  = form.save(commit=False)
            complaint.user = request.user
            complaint.save()
            complaints = Complaint.objects.filter(user=request.user)
            return render(request, 'welfare/complaints.html', {'complaints':complaints})
        else:
            return render(request, 'welfare/complaint.html', {'form':form})


def complaints(request):
    if not request.user.is_authenticated():
        return render(request, 'profiles/login.html')
    else:
        complaints = Complaint.objects.filter(user=request.user)
        return render(request, 'welfare/complaints.html', {'complaints':complaints})

Dashboard/templates/welfare/base.html
<!DOCTYPE html>
  <html>
    <head>
        <title>{% block title %}Welfare-Portal{% endblock %}</title>
		<link href='https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css' rel='stylesheet'
			type='text/css'>
      <!--Import Google Icon Font-->
      <link href="http://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
      <!--Import materialize.css-->
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.98.0/css/materialize.min.css"  media="screen,projection"/>
		{% load staticfiles %}
		<link rel="stylesheet" type="text/css" href="{% static 'terashare/base.css' %}"/>

      <!--Let browser know website is optimized for mobile-->
      <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    {% block css %} {% endblock %}
    </head>

    <body>
		<nav>
			<div class="nav-wrapper indigo darken-3">
			  <ul class="brand-logo left" id="gnius">GNius</ul>
			  <a href="" data-activates="mobile-demo" class="button-collapse right"><i class="material-icons">menu</i></a>

			  <ul class="brand-logo center hide-on-med-and-down">
				<li><a  href="{% url 'home:home' %}">Home</a></li>
				<li><a  href="{% url 'terashare:home' %}">TeraShare</a></li>
				<li><a href="{% url 'timetable:table' %}">Time Table</a></li>
                  <li><a class="active" href="{% url 'welfare:home' %}">Welfare</a></li>
                  <li><a href="{% url 'parcel:parcels' %}" >Parcel</a></li>
                  <li><a  href="{% url 'shuttleservice:buses' %}">Shuttle</a></li>
                  <li><a  href="{% url 'rooms:home' %}">Rooms</a></li>
                  <li><a href="{% url 'lostfound:homelost' %}">Lost/Found</a></li>
			  </ul>

				<ul class="brand-logo right hide-on-med-and-down">
				 <li><a href="{% url 'profiles:logout_user' %}"><i class="material-icons">exit_to_app</i></a></li>
				<li><a href="#" data-letters="{{ request.user.username|upper|make_list|first }}" class="letters"></a></li>
			  </ul>

			<ul class="side-nav right indigo darken-3" id="mobile-demo">
				<li><a href="{% url 'home:home' %}">Home</a></li>
				<li><a  href="{% url 'terashare:home' %}">TeraShare</a></li>
				<li><a href="{% url 'timetable:table' %}">Time Table</a></li>
                <li><a  class="active" href="{% url 'welfare:home' %}">Welfare</a></li>
                <li><a href="{% url 'parcel:parcels' %}" >Parcel</a></li>
                <li><a href="{% url 'shuttleservice:buses' %}">Shuttle</a></li>
                <li><a  href="{% url 'rooms:home' %}">Rooms</a></li>
                  <li><a href="{% url 'lostfound:homelost' %}">Lost/Found</a></li>
				 <li><a href="{% url 'profiles:logout_user' %}"><i class="material-icons">exit_to_app</i></a></li>
				<li><a href="#" data-letters="{{ request.user.username|upper|make_list|first }}" class="letters"></a></li>	</ul>

			</div>
  		</nav>
  		<div class="section indigo darken-1 center" style="color: #ffffff; padding: 20px;">
  			{% block titl %}Hello! {{ request.user.username }}{% endblock %}
  		</div>
		<script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.98.0/js/materialize.min.js"></script>
		<script>
			 $(".button-collapse").sideNav({edge: 'right'});
		</script>

    {% block body %}

    {% endblock %}
	  </body>
</html>

Dashboard/templates/welfare/complaint.html
{% extends 'welfare/base.html' %}
{% block css %}
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'welfare/complaint.css' %}">
{% endblock %}
{% block titl %}
    Complaint your issue
{% endblock %}
{% block body %}
    <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="container">
	  		<div class="row">
	  			<div class="container">
	  				<div class="row">
						<div class="form-box center">
                            {% for field in form %}
                                <div class="non input-field left" style="color: #ffffff">
								{{ field.label }}
                                    </div>
                            <div class="input-field">
                                <div class="input-field">
                                    {{ field }}
                                </div>
                            </div>
                            {% endfor %}
                        <div class="input-field">
							<input class="center" type="submit" name="submit_btn" value="Complain">
							</div><br>
                            <div class="right"><a href="{% url 'welfare:home' %}"><i class="material-icons" style="color: white;">arrow_forward</i></a></div>
                        </div>
                        </div>
                    </div>
				</div>
			</div>
</form>

    <script>
    $('select').material_select();
    $('')
    </script>
{% endblock %}

Dashboard/templates/welfare/complaints.html
{% extends 'welfare/base.html' %}
{% block css %}
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'terashare/file.css' %}">
{% endblock %}
{% block titl %}
    Your complaints and status
{% endblock %}
{% block body %}

<div class="container">
  		<div class="row">
  			<div class="container">
  				<div class="row">
					<div class="search center">
                        <div class="search-section"><input type="text" id="myInput" onkeyup="myFunction()" class="search-box" placeholder="Search for Books and so on"><a class="upload-button" href="{% url 'welfare:register' %}"><div class="tiny material-icons">edit</div></a><button type="submit" class="search-button"><div class="tiny material-icons">search</div></button>
						</div>
					</div>

					<div class="browse">
						<nav class="smaller-nav">
							<div class="nav-wrapper indigo darken-3">
								  <ul class="brand-logo">
                                      <li><a href="#">Complaints</a></li>
								  </ul>

                        </div>
						</nav>
					</div>
					<div class="searched-items">
					<ul class="collection" id="myUL">
                    <script type="text/javascript">
                        var flag = false
                    </script>
                        {% for complaint in complaints %}
                                <script type="text/javascript">
                                     var flag = true
                                </script>
                                <li class="collection-item avatar">
					                <span class="title">{{ complaint }} ( {{ complaint.Category }} )</span>
					                <p>{{ complaint.Description }}</p>
                                    <div><button class="download-button">{% if complaint.is_resolved %}Resolved{% else %}Pending{% endif %}</button></div>
					            </li>
                        {% endfor %}
					  </ul>
                        <script>
                           if (flag == false) {
                               document.write("<h3>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;No Complaints yet</h3>")
                           }
                        </script>
					</div>
				</div>
			</div>
		</div>
	</div>
    <script>

jQuery(document).ready(function($){

$('.collection li').each(function(){
$(this).attr('data-search-term', $(this).text().toLowerCase());
});

$('.search-box').on('keyup', function(){

var searchTerm = $(this).val().toLowerCase();

    $('.collection li').each(function(){

        if ($(this).filter('[data-search-term *= ' + searchTerm + ']').length > 0 || searchTerm.length < 1) {
            $(this).show();
        } else {
            $(this).hide();
        }

    });

});

});
</script>

{% endblock %}

Dashboard/templates/welfare/home.html
{% extends 'welfare/base.html' %}
{% block css %}
    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'terashare/home.css' %}">
{% endblock %}
{% block titl %}
    Don't wait to complain
{% endblock %}
{% block body %}
<div class="container">
	  		<div class="row">
	  			<div class="container">
	  				<div class="row contents-box">

							<div class="col s12 m6">
								<h4>Welfare problems?</h4>
								<h6>This complaint box guarantees responses!</h6>
                                <div class="col s12 m6 center"><a href="{% url 'welfare:register' %}" ><button class="upload-btn">Complaint</button></a></div>
                                <div class="col s12 m6 center"><a href="{% url 'welfare:complaints' %}"><button class="search-btn">Complaints</button></a></div>
							</div>
							<div class="col s12 m6" align="right" style="padding-right: 0px;">
								<img src="{% static 'welfare/images/welfare (1).png' %}" style="height:70px; width: 100px;">
							</div>

					</div>
				</div>
			</div>
		</div>
{% endblock %}