Dashboard/Dashboard/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^mess/', include('mess.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^terashare/', include('terashare.urls')),
    url(r'', include('profiles.urls')),
    url(r'^timetable/', include('timetable.urls')),
    url(r'^parcel/', include('parcels.urls')),
    url(r'^shuttle/', include('shuttleservice.urls')),
    url(r'^welfare/', include('welfare.urls')),
    url(r'^rooms/', include('rooms.urls')),
    url(r'^', include('home.urls')),
    url(r'^lostfound/',include('lostfound.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Dashboard/home/urls.py
from django.conf.urls import url
from . import views

app_name = 'home'

urlpatterns = [
    url(r'^$', views.Home, name='home')
]

Dashboard/parcels/urls.py
from django.conf.urls import url
from . import views

app_name = 'parcel'


urlpatterns = [
    url(r'^$', views.homepage, name='parcels')
]

Dashboard/profiles/urls.py
from django.conf.urls import url
from . import views

app_name = 'profiles'

urlpatterns = [
    url(r'^register/$', views.register, name='register'),
    url(r'^login', views.login_user, name='login_user'),
    url(r'^logout', views.logout_user, name='logout_user'),
    url(r'^home', views.home, name='home')
]

Dashboard/rooms/urls.py
from django.conf.urls import url
from django.contrib import admin
from . import views

app_name='rooms'

urlpatterns=[
    url(r'^$',views.HomeView,name='home'),
    url(r'^requestroom$',views.RequestView,name='requestroom'),
    url(r'^viewrequest$',views.ShowView,name='showrequest'),
    url(r'^detail$', views.DetailView, name='detail'),


  ]

Dashboard/terashare/urls.py
from django.conf.urls import url
from . import views

app_name = 'terashare'

urlpatterns = [
    url(r'^home/$', views.home, name='home'),
    url(r'^course/(?P<course_id>[0-9]+)/(?P<folder_id>[0-9]+)/$', views.files, name='files'),
    url(r'^(?P<course_id>[0-9]+)/(?P<folder_id>[0-9]+)/(?P<file_id>[0-9]+)/download/$', views.download, name='download'),
    url(r'^(?P<course_id>[0-9]+)/(?P<folder_id>[0-9]+)/(?P<file_id>[0-9]+)/report/$', views.report, name='report'),
    url(r'^upload/$', views.upload, name='upload'),
    url(r'^search/$', views.search, name='search_course'),
    url(r'^search/results/$', views.searchres, name='search_results'),

]

Dashboard/welfare/urls.py
from django.conf.urls import url
from . import views

app_name = 'welfare'

urlpatterns = [
    url(r'^home/$', views.Home, name='home'),
    url(r'^complain/$', views.complaint, name='register'),
    url(r'^complaints/$', views.complaints, name='complaints')
]

Dashboard/home/models.py
from django.db import models

# Create your models here.

Dashboard/terashare/models.py
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models
from os import path
from datetime import datetime


class Course(models.Model):
    course_title = models.CharField(max_length=6)
    course_code = models.CharField(max_length=3, null=True)
    Sun = models.BooleanField()
    Mon = models.BooleanField()
    Tue = models.BooleanField()
    Wed = models.BooleanField()
    Thu = models.BooleanField()
    Fri = models.BooleanField()
    Sat = models.BooleanField()
    From = models.TimeField()
    To = models.TimeField()

    def __str__(self):
        return self.course_title + ' - ' + self.course_code

    def courses_today(self, num):
        c = {7:self.Sun, 1:self.Mon, 2:self.Tue, 3:self.Wed, 4:self.Thu, 5:self.Fri, 6:self.Sat}
        return c[num]
    @property
    def is_present(self):
        now = datetime.now().isoweekday()
        return Course.courses_today(self, now)


class Folder(models.Model):
    folder = models.CharField(max_length=255, unique=True)

    def __str__(self):
        return self.folder


class File(models.Model):
    Title = models.CharField(max_length=150)
    Stream = models.CharField(max_length=150, null=True)
    Course = models.ForeignKey(Course, on_delete=models.CASCADE)
    Type = models.ForeignKey(Folder, on_delete=models.CASCADE)
    file = models.FileField()
    updated = models.DateTimeField(auto_now=True, auto_now_add=False)
    timestamp = models.DateTimeField(auto_now=False, auto_now_add=True)
    report = models.BooleanField(default=False)

    def filename(self):
        return path.basename(self.file.name)

    def __str__(self):
        return self.Title

Dashboard/terashare/forms.py
from django import forms
from .models import File


class FileForm(forms.ModelForm):
    class Meta:
        model = File
        fields = ['Title', 'Stream', 'Course', 'Type', 'file']

Dashboard/home/views.py
from django.shortcuts import render

# Create your views here.
def Home(request):
    if not request.user.is_authenticated():
        return render(request, 'profiles/home.html')
    else:
        return render(request, 'home/home.html')

Dashboard/terashare/views.py
from django.db.models import Q
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404, redirect
from .models import File, Folder, Course
from .forms import FileForm
from django.contrib.auth import authenticate


def files(request, course_id, folder_id):
    if not request.user.is_authenticated():
        return render(request, 'profiles/login.html')
    else:
        course = get_object_or_404(Course, pk=course_id)
        folder = get_object_or_404(Folder, pk=folder_id)
        all_courses = Course.objects.all()
        all_files = File.objects.all()
        all_folders = Folder.objects.all()
        return render(request, 'terashare/file.html',
                      {'all_courses': all_courses, 'all_files': all_files, 'all_folders': all_folders,
                       'course_id': course_id, 'course': course, 'folder': folder, 'folder_id': folder_id})


def home(request):
    if not request.user.is_authenticated():
        return render(request, 'profiles/login.html')
    else:
        return render(request, 'terashare/home.html')


def download(request, course_id, folder_id, file_id):
    if not request.user.is_authenticated():
        return render(request, 'profiles/login.html')
    else:
        file = get_object_or_404(File, pk=file_id)
        folder = get_object_or_404(Folder, pk=folder_id)
        course = get_object_or_404(Course, pk=course_id)
        req_file = file.filename()
        file_download = file.file
        response = HttpResponse(file_download.file, content_type='text/plain')
        response['Content-Disposition'] = 'attachment; filename=%s' % req_file
        return response


def report(request, course_id, folder_id, file_id):
    if not request.user.is_authenticated():
        return render(request, 'profiles/login.html')
    else:
        return HttpResponse("i")


ebook_file_types = ['pdf', 'doc', 'docx', 'epub', 'pdb', 'html', 'txt', 'mobi']


def upload(request):
    if not request.user.is_authenticated():
        return render(request, 'profiles/login.html')
    else:
        all_courses = Course.objects.all()
        all_folders = Folder.objects.all()
        all_files = File.objects.all()
        form = FileForm(request.POST or None, request.FILES or None)
        if form.is_valid():
            book = form.save(commit=False)
            course = book.Course
            course_id = book.Course.id
            folder = book.Type
            folder_id = book.Type.id
            file_type = book.filename().split('.')[-1]
            file_type = file_type.lower()
            if file_type not in ebook_file_types:
                context = {
                    'form': form,
                    'error_message': 'Unsupported File Format',
                    'all_folders': all_folders,
                    'all_courses': all_courses,
                }
                return render(request, 'terashare/upload.html', context)
            book.save()
            context = {'all_courses': all_courses, 'all_folders': all_folders, 'all_files': all_files, 'course': course,
                       'folder': folder, 'course_id': course_id, 'folder_id': folder_id}
            return render(request, 'terashare/file.html', context)
        context = {'form': form, 'all_folders': all_folders, 'all_courses': all_courses}
        return render(request, 'terashare/upload.html', context)


def search(request):
    if not request.user.is_authenticated():
        return render(request, 'profiles/login.html')
    else:
        all_courses = Course.objects.all()
        query = request.GET.get("q")
        if query:
            query = query.split()
            for i in query:
                all_courses = all_courses.filter(
                    Q(course_code__icontains=i) |
                    Q(course_title__icontains=i)).distinct()
            context = {'all_courses': all_courses}
            return render(request, 'terashare/search_results.html', context)
        return render(request, 'terashare/search.html')


def searchres(request):
    if not request.user.is_authenticated():
        return render(request, 'profiles/login.html')
    else:
        return render(request, 'terashare/home.html')

Dashboard/templates/terashare/base.html
<!DOCTYPE html>
  <html>
    <head>
        <title>{% block title %}Terashare{% endblock %}</title>
		<link href='https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css' rel='stylesheet'
			type='text/css'>
      <!--Import Google Icon Font-->
      <link href="http://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
      <!--Import materialize.css-->
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.98.0/css/materialize.min.css"  media="screen,projection"/>
		{% load staticfiles %}
		<link rel="stylesheet" type="text/css" href="{% static 'terashare/base.css' %}"/>

      <!--Let browser know website is optimized for mobile-->
      <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    {% block css %} {% endblock %}
    </head>

    <body>
		<nav>
			<div class="nav-wrapper indigo darken-3">
			  <ul class="brand-logo left" id="gnius">GNius</ul>
			  <a href="" data-activates="mobile-demo" class="button-collapse right"><i class="material-icons">menu</i></a>

			  <ul class="brand-logo center hide-on-med-and-down">
				<li><a  href="{% url 'home:home' %}">Home</a></li>
				<li><a class="active" href="{% url 'terashare:home' %}">TeraShare</a></li>
				<li><a href="{% url 'timetable:table' %}">Time Table</a></li>
                  <li><a href="{% url 'welfare:home' %}">Welfare</a></li>
                  <li><a href="{% url 'parcel:parcels' %}" >Parcel</a></li>
                  <li><a href="{% url 'shuttleservice:buses' %}">Shuttle</a></li>
                  <li><a  href="{% url 'rooms:home' %}">Rooms</a></li>
                  <li><a href="{% url 'lostfound:homelost' %}">Lost/Found</a></li>
			  </ul>

				<ul class="brand-logo right hide-on-med-and-down">
				<li><a href="{% url 'profiles:logout_user' %}"><i class="material-icons">exit_to_app</i></a></li>
				<li><a href="#" data-letters="{{ request.user.username|upper|make_list|first }}" class="letters"></a></li>

			  </ul>

			<ul class="side-nav right indigo darken-3" id="mobile-demo">
				<li><a href="{% url 'home:home' %}">Home</a></li>
				<li><a class="active" href="{% url 'terashare:home' %}">TeraShare</a></li>
				<li><a href="{% url 'timetable:table' %}">Time Table</a></li>
                <li><a href="{% url 'welfare:home' %}">Welfare</a></li>
                <li><a href="{% url 'parcel:parcels' %}" >Parcel</a></li>
                <li><a href="{% url 'shuttleservice:buses' %}">Shuttle</a></li>
                <li><a  href="{% url 'rooms:home' %}">Rooms</a></li>
                  <li><a href="{% url 'lostfound:homelost' %}">Lost/Found</a></li>
				  <li><a href="{% url 'profiles:logout_user' %}"><i class="material-icons">exit_to_app</i></a></li>
				<li><a href="#" data-letters="{{ request.user.username|upper|make_list|first }}" class="letters"></a></li>
			</ul>

			</div>
  		</nav>
  		<div class="section indigo darken-1 center" style="color: #ffffff; padding: 20px;">
  			{% block titl %}Hello! {{ request.user.username }}{% endblock %}
  		</div>
		<script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.98.0/js/materialize.min.js"></script>
		<script>
			 $(".button-collapse").sideNav({edge: 'right'});
		</script>

    {% block body %}

    {% endblock %}
	  </body>
</html>

Dashboard/templates/terashare/file.html
{% extends 'terashare/base.html' %}
{% block css %}
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'terashare/file.css' %}">
{% endblock %}
{% block titl %}
    {{ course }}
{% endblock %}
{% block body %}
<div class="container">
  		<div class="row">
  			<div class="container">
  				<div class="row">
					<div class="search center">
                        <div class="search-section"><input type="text"  onkeyup="myFunction()" class="search-box" placeholder="Search to filter"><a class="upload-button" href="{% url 'terashare:upload' %}"><div class="tiny material-icons">file_upload</div></a><button type="submit" class="search-button"><div class="tiny material-icons"><a href="{% url 'terashare:search_course' %}">search</a></div></button>
						</div>
					</div>

					<div class="browse">
						<nav class="smaller-nav">
							<div class="nav-wrapper indigo darken-3">
								  <ul class="brand-logo hide-on-med-and-down">
                                      {% for folders in all_folders %}
                                          <li><a class="{% if folder == folders %}active-small{% endif %}"  href="{% url 'terashare:files' course.id folders.id %}">{{ folders }}</a></li>
                                      {% endfor %}
                                  </ul>
								  <a href="#" data-activates="mobile-demo-2" class="button-collapse right"><i class="material-icons">menu</i></a>
								  <ul class="side-nav right indigo darken-3" id="mobile-demo-2" >
                                      {% for folder in all_folders %}
                                          <li><a href="{% url 'terashare:files' course.id folder.id %}">{{ folder }}</a></li>
                                      {% endfor %}
									<li><a href="#">Others<i class="fa fa-caret-down right"></i></a></li>
									</ul>
                        </div>
						</nav>
					</div>
					<div class="searched-items">
					<ul class="collection" class="live-search-list">
                    <script type="text/javascript">
                        var flag = false
                    </script>
                        {% for file in all_files %}
                            {% if file.Course == course and file.Type == folder %}
                                <script type="text/javascript">
                                     var flag = true
                                </script>
                                <li class="collection-item avatar">
					                <span class="title">{{ file.Title }}</span>
					                <p>{{ file.filename }}</p>
                                   <a class="secondary-content"><a class="add-white" href="{% url 'terashare:download' course_id folder_id file.id %}"><button class="download-button"> Download</button></a><a class="add-white" href="#"><button class="report-button" href="#">Report</button></a></a>
					            </li>
                            {% endif %}
                        {% endfor %}
					  </ul>
                        <script>
                           if (flag == false) {
                               document.write("<h5>Sorry no files <i class='material-icons'>receipt</i></h5>")
                           }
                        </script>
					</div>
				</div>
			</div>
		</div>
	</div>
<script>
$("button-collapse").sideNav({edge: 'right'});
$jQuery(document).ready(function($){

$('.collection li').each(function(){
$(this).attr('data-search-term', $(this).text().toLowerCase());
});

$('.search-box').on('keyup', function(){

var searchTerm = $(this).val().toLowerCase();

    $('.collection li').each(function(){

        if ($(this).filter('[data-search-term *= ' + searchTerm + ']').length > 0 || searchTerm.length < 1) {
            $(this).show();
        } else {
            $(this).hide();
        }

    });

});

});



</script>
{% endblock %}

Dashboard/templates/terashare/home.html
{% extends 'terashare/base.html' %}
{% block css %}
    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'terashare/home.css' %}">
{% endblock %}
{% block titl %}
    Welcome to Terashare
{% endblock %}
{% block body %}
<div class="container">
	  		<div class="row">
	  			<div class="container">
	  				<div class="row contents-box">

							<div class="col s12 m6">
								<h4>Sharing is caring!</h4>
								<h6>Knowledge increases when it is spread. <br> Reap the benefits of what you share!</h6>
                                <div class="col s12 m6 center"><a href="{% url 'terashare:upload' %}" ><button class="upload-btn">Upload</button></a></div>
                                <div class="col s12 m6 center"><a href="{% url 'terashare:search_course' %}"><button class="search-btn">Search</button></a></div>
							</div>
							<div class="col s12 m6" align="right" style="padding-right: 0px;">
								<img src="{% static 'terashare/images/welcome.jpeg' %}" style="margin-right: 0px;">
							</div>

					</div>
				</div>
			</div>
		</div>
{% endblock %}

Dashboard/templates/terashare/search.html
{% extends 'terashare/base.html' %}
{% block css %}
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'terashare/search.css' %}">
{% endblock %}
{% block titl %}
    Search the course
{% endblock %}
{% block body %}

    <div class="container">
	  		<div class="row">
	  			<div class="container">
	  				<div class="row contents-box">

							<div class="col s12 m12 center">
								<h4>Sharing is caring!</h4>
								<h6>Knowledge increases when it is spread. <br> Reap the benefits of what you share!</h6>
							</div>
                        <div class="col s12 m12 center search">
                            <form class="form-inline my-2 my-lg-0" method='GET' action='' >
                            <input type="text" class="search-box" name="q" value="{{ request.GET.q }}" placeholder="Search for Courses here"><button type="submit" class="search-button"><i class="tiny material-icons">search</i></button>
                            </form>
                        </div>


					</div>
					<div class="row main-box">
                        <a href="{% url 'terashare:home' %}" ><i class="material-icons" style="color: white;">arrow_backward</i></a>
					</div>
				</div>

			</div>
		</div>

{% endblock %}

Dashboard/templates/terashare/search_results.html
{% extends 'terashare/base.html' %}
{% block css %}
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'terashare/file.css' %}">
{% endblock %}
{% block titl %}
    Matched courses
{% endblock %}
{% block body %}

<div class="container">
  		<div class="row">
  			<div class="container">
  				<div class="row">
					<div class="search center">
                        <div class="search-section"><input type="text" id="myInput" onkeyup="myFunction()" class="search-box" placeholder="Search for Books and so on"><a class="upload-button" href="{% url 'terashare:upload' %}"><div class="tiny material-icons">file_upload</div></a><button type="submit" class="search-button"><div class="tiny material-icons"><a href="{% url 'terashare:search_course' %}">search</a></div></button>
						</div>
					</div>

					<div class="browse">
						<nav class="smaller-nav">
							<div class="nav-wrapper indigo darken-3">
								  <ul class="brand-logo hide-on-med-and-down">
                                      <li><a href="#">Courses</a></li>
								  </ul>
								  <a href="" data-activates="mobile-demo-2" class="button-collapse right"><i class="material-icons">chevron_right</i></a>
								  <ul class="side-nav right indigo darken-3" id="mobile-demo-2" >
                                          <li><a href="#">Course</a></li>
									</ul>
                        </div>
						</nav>
					</div>
					<div class="searched-items">
					<ul class="collection" id="myUL">
                    <script type="text/javascript">
                        var flag = false
                    </script>
                        {% for course in all_courses %}
                                <script type="text/javascript">
                                     var flag = true
                                </script>
                                <li class="collection-item avatar">
					                <span class="title">{{ course }}</span>
					                <p><a href={% url 'terashare:files' course.id 1%}>{{ course }}</a></p>
					            </li>
                        {% endfor %}
					  </ul>
                        <script>
                           if (flag == false) {
                               document.write("<h3 class='center'>No results</h3>")
                           }
                        </script>
					</div>
				</div>
			</div>
		</div>
	</div>
    <script>
function myFunction() {
    // Declare variables
    var input, filter, ul, li, a, i;
    input = document.getElementById('myInput');
    filter = input.value.toUpperCase();
    ul = document.getElementById("myUL");
    li = ul.getElementsByTagName('li');

    // Loop through all list items, and hide those who don't match the search query
    for (i = 0; i < li.length; i++) {
        a = li[i].getElementsByTagName("a")[0];
        if (a.innerHTML.toUpperCase().indexOf(filter) > -1) {
            li[i].style.display = "";
        } else {
            li[i].style.display = "none";
        }
    }
}
</script>

{% endblock %}

Dashboard/templates/terashare/upload.html
{% extends 'terashare/base.html' %}

{% block title %} Upload {% endblock %}

{% block css%}
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'terashare/upload.css' %}">
{% endblock %}
{% block titl %}
    Upload file
{% endblock %}
{% block body %}

<form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="container">
	  		<div class="row">
	  			<div class="container">
	  				<div class="row">
						<div class="form-box center">
                            {% for field in form %}
                                {% if field.label != "File" %}
                                    <div class="non input-field left" style="color: #ffffff">
								{{ field.label }}
                                    </div>
                                   <div class="input-field">
                                            <div class="input-field">
                                                {{ field }}
                                            </div>
                                    </div>
                                    {% else %}
                                    <div class="input-field">
                                            <div class="input-field" id="choose-file">
                                                Choose-file
                                                {{ field }}
                                            </div>
                                    </div>
                                {% endif %}

                                            {% endfor %}
                            <div class="input-field">
							<input class="center" type="submit" name="submit_btn" value="Upload">
							</div><br>
                            <div class="left"><a href="{% url 'terashare:home' %}"><i class="material-icons" style="color: white;">arrow_backward</i></a></div>
                        </div>
                    </div>
				</div>
			</div>
		</div>
</form>

    <script>
    $('select').material_select();
    $('')
    </script>

{% endblock %}