Dashboard/Dashboard/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^mess/', include('mess.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^terashare/', include('terashare.urls')),
    url(r'', include('profiles.urls')),
    url(r'^timetable/', include('timetable.urls')),
    url(r'^parcel/', include('parcels.urls')),
    url(r'^shuttle/', include('shuttleservice.urls')),
    url(r'^welfare/', include('welfare.urls')),
    url(r'^rooms/', include('rooms.urls')),
    url(r'^', include('home.urls')),
    url(r'^lostfound/',include('lostfound.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Dashboard/home/urls.py
from django.conf.urls import url
from . import views

app_name = 'home'

urlpatterns = [
    url(r'^$', views.Home, name='home')
]

Dashboard/lostfound/urls.py
from django.conf.urls import url
from django.contrib import admin
from . import views

app_name='lostfound'

urlpatterns=[
    url(r'^$',views.HomeView,name='homelost'),
    url(r'^reportlost$',views.LostView,name='reportlost'),
    url(r'^reportfound$',views.FoundView,name='reportfound'),
    url(r'^matchfound$',views.CompareView,name='matchfound'),
 ]

Dashboard/parcels/urls.py
from django.conf.urls import url
from . import views

app_name = 'parcel'


urlpatterns = [
    url(r'^$', views.homepage, name='parcels')
]

Dashboard/profiles/urls.py
from django.conf.urls import url
from . import views

app_name = 'profiles'

urlpatterns = [
    url(r'^register/$', views.register, name='register'),
    url(r'^login', views.login_user, name='login_user'),
    url(r'^logout', views.logout_user, name='logout_user'),
    url(r'^home', views.home, name='home')
]

Dashboard/rooms/urls.py
from django.conf.urls import url
from django.contrib import admin
from . import views

app_name='rooms'

urlpatterns=[
    url(r'^$',views.HomeView,name='home'),
    url(r'^requestroom$',views.RequestView,name='requestroom'),
    url(r'^viewrequest$',views.ShowView,name='showrequest'),
    url(r'^detail$', views.DetailView, name='detail'),


  ]

Dashboard/welfare/urls.py
from django.conf.urls import url
from . import views

app_name = 'welfare'

urlpatterns = [
    url(r'^home/$', views.Home, name='home'),
    url(r'^complain/$', views.complaint, name='register'),
    url(r'^complaints/$', views.complaints, name='complaints')
]

Dashboard/lostfound/models.py
from django.db import models

# Create your models here.
class Lost(models.Model):
    Item_Name = models.CharField(max_length=100)
    Item_Image=models.ImageField(default="\static\lostfound\images\empty.png")
    Description = models.TextField(max_length=500)
    Last_Seen = models.CharField(max_length=200)
    updated = models.DateTimeField(auto_now=True, auto_now_add=False)
    timestamp = models.DateTimeField(auto_now=False, auto_now_add=True)

    def __str__(self):
        return self.Item_Name

class Found(models.Model):
    Item_Name = models.CharField(max_length=100)
    Item_Image=models.ImageField(default="\static\lostfound\images\empty.png")
    Description = models.TextField(max_length=500)
    Found_on = models.CharField(max_length=200)
    updated = models.DateTimeField(auto_now=True, auto_now_add=False)
    timestamp = models.DateTimeField(auto_now=False, auto_now_add=True)

    def __str__(self):
        return self.Item_Name

Dashboard/lostfound/forms.py
from django import forms
from .models import Lost
from .models import Found
from django.forms import ModelForm


class LostForm(ModelForm):

    class Meta:
        model = Lost
        fields = ['Item_Name','Item_Image','Description','Last_Seen']



class FoundForm(ModelForm):
    class Meta:
        model = Found
        fields=['Item_Name','Item_Image','Description','Found_on']

Dashboard/lostfound/views.py
from django.shortcuts import render
from .models import Lost
from .models import Found
from .forms import LostForm
from .forms import FoundForm
from django.shortcuts import redirect
from django.contrib import messages
from difflib import SequenceMatcher


def similar(a, b):
    return SequenceMatcher(None, a, b).ratio()

def HomeView(request):
    return render(request,'lostfound/homelost.html')


def LostView(request):
    form = LostForm(request.POST or None, request.FILES or None)
    if request.method == 'POST':
        if form.is_valid():
            form.save()
            messages.success(request, "Form Submitted ")
            return redirect('lostfound:homelost')
        else:
            messages.error(request, "The Details were not Registered, Please Try Again")
    context = {"form":form}
    return render(request, 'lostfound/reportlost.html', context)



def FoundView(request):
    form = FoundForm(request.POST or None, request.FILES or None)
    if request.method == 'POST':
        if form.is_valid():
            form.save()
            messages.success(request, "Form Submitted ")
            return redirect('lostfound:homelost')
        else:
            messages.error(request, "The Details were not Registered, Please Try Again")
    context = {"form":form}
    return render(request, 'lostfound/reportfound.html', context)

def CompareView(request):
    lst=[]
    for obj1 in Lost.objects.all():
        res = False
        lst.append(obj1.Item_Name +':' + obj1.Last_Seen +':' + obj1.Description)
        for obj2 in Found.objects.all():
            if similar(obj1.Item_Name,obj2.Item_Name)>0.8:
                    if obj2.Found_on > obj1.Last_Seen :#obj2.Found_on__gte=obj1.Last_seen
                        str2="We found a match:"
                        str2+=(obj2.Item_Name + ':' + obj2.Found_on +':'+ obj2.Description)
                        lst.append(str2)
                        res=True
        if res==False:
            lst.append("Sorry, no matches found")
    return render(request,'lostfound/matches.html',{"lst":lst})

Dashboard/templates/lostfound/base.html
<!DOCTYPE html>
  <html>
    <head>
        <title>{% block title %}Terashare{% endblock %}</title>
		<link href='https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css' rel='stylesheet'
			type='text/css'>
      <!--Import Google Icon Font-->
      <link href="http://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
      <!--Import materialize.css-->
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.98.0/css/materialize.min.css"  media="screen,projection"/>
		{% load staticfiles %}
		<link rel="stylesheet" type="text/css" href="{% static 'terashare/base.css' %}"/>

      <!--Let browser know website is optimized for mobile-->
      <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    {% block css %} {% endblock %}
    </head>

    <body>
		<nav>
			<div class="nav-wrapper indigo darken-3">
			  <ul class="brand-logo left" id="gnius">GNius</ul>
			  <a href="" data-activates="mobile-demo" class="button-collapse right"><i class="material-icons">menu</i></a>

			  <ul class="brand-logo center hide-on-med-and-down">
				<li><a  href="{% url 'home:home' %}">Home</a></li>
				<li><a href="{% url 'terashare:home' %}">TeraShare</a></li>
				<li><a href="{% url 'timetable:table' %}">Time Table</a></li>
                  <li><a href="{% url 'welfare:home' %}">Welfare</a></li>
                  <li><a href="{% url 'parcel:parcels' %}" >Parcel</a></li>
                  <li><a href="{% url 'shuttleservice:buses' %}">Shuttle</a></li>
                  <li><a  href="{% url 'rooms:home' %}">Rooms</a></li>
                   <li><a class="active" href="{% url 'lostfound:homelost' %}">Lost/Found</a></li>
			  </ul>

				<ul class="brand-logo right hide-on-med-and-down">
				<li><a href="{% url 'profiles:logout_user' %}"><i class="material-icons">exit_to_app</i></a></li>
				<li><a href="#" data-letters="{{ request.user.username|upper|make_list|first }}" class="letters"></a></li>

			  </ul>

			<ul class="side-nav right indigo darken-3" id="mobile-demo">
				<li><a href="{% url 'home:home' %}">Home</a></li>
				<li><a  href="{% url 'terashare:home' %}">TeraShare</a></li>
				<li><a href="{% url 'timetable:table' %}">Time Table</a></li>
                <li><a href="{% url 'welfare:home' %}">Welfare</a></li>
                <li><a href="{% url 'parcel:parcels' %}" >Parcel</a></li>
                <li><a href="{% url 'shuttleservice:buses' %}">Shuttle</a></li>
                <li><a  href="{% url 'rooms:home' %}">Rooms</a></li>
                  <li><a class="active" href="{% url 'lostfound:homelost' %}">Lost/Found</a></li>
				  <li><a href="{% url 'profiles:logout_user' %}"><i class="material-icons">exit_to_app</i></a></li>
				<li><a href="#" data-letters="{{ request.user.username|upper|make_list|first }}" class="letters"></a></li>
			</ul>

			</div>
  		</nav>
  		<div class="section indigo darken-1 center" style="color: #ffffff; padding: 20px;">
  			{% block titl %}Hello! {{ request.user.username }}{% endblock %}
  		</div>
		<script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.98.0/js/materialize.min.js"></script>
		<script>
			 $(".button-collapse").sideNav({edge: 'right'});
		</script>

    {% block body %}

    {% endblock %}
	  </body>
</html>

Dashboard/templates/lostfound/homelost.html
{% extends 'lostfound/base.html' %}
{% block css %}
    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'terashare/home.css' %}">
    {% block title %}
        Lost/Found
        {% endblock %}
{% endblock %}
{% block titl %}
    Lost & Found :(
{% endblock %}
{% block body %}
<div class="container">
	  		<div class="row">
	  			<div class="container">
	  				<div class="row contents-box">

							<div class="col s12 m6">
								<h4>Lost Something? <br>Found Something??<br>Let Others know:</h4>
                         <div class="col s12 center"><button class="upload-btn"><a href="{% url 'lostfound:reportlost' %}">Lost</a></button></div>
                         <div class="col s12 center"><button class="upload-btn"><a href="{% url 'lostfound:reportfound' %}">Found</a></button></div>
                         <div class="col s12 center"><button class="upload-btn"><a href="{% url 'lostfound:matchfound' %}">Check for Matches</a></button></div></div>
							<div class="col s12 m6" align="right" style="padding-right: 0px;">
							</div>

					</div>
				</div>
			</div>
		</div>
{% endblock %}

Dashboard/templates/lostfound/matches.html
{% extends 'lostfound/base.html' %}
{% block css %}
    <style>.contents-box
			{
				margin-top: 3rem;
				background: rgba(63,81,181,1);
				padding: 50px;
				color: #ffffff;
			}
			.form-btn
			{
				background-color: #ff4086;
				border: 0px;
				margin-top: 20px;
				padding: 10px;
				color: #ffffff;
			}</style>
{% endblock %}
{% block titl %}
    Lost & Found :(
{% endblock %}
{% block body %}
<div class="container">
	  		<div class="row">
	  			<div class="container">
	  				<div class="row contents-box">
                        <ul id="listed">

                        </ul>
					</div>
				</div>
			</div>
		</div>
		<script>
			 $(".button-collapse").sideNav({edge: 'right'});
            $(document).ready(function(){
                var x = {{ lst|safe }};
                var l = x.length;
                printing = "";
                for (var i=0; i<l;i++)
                {
                    printing = printing+"<li>"+x[i]+"</li>"+"<br>";
                    if (i%2 != 0) {
                        printing = printing + "<br>";
                    }
                }
                $('#listed').html(printing);


            });
        </script>
{% endblock %}

Dashboard/templates/lostfound/reportfound.html
{% extends 'lostfound/base.html' %}

{% block title %} Found {% endblock %}

{% block css%}
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'terashare/upload.css' %}">
{% endblock %}
{% block titl %}
    Report Found
{% endblock %}
{% block body %}

<form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="container">
	  		<div class="row">
	  			<div class="container">
	  				<div class="row">
						<div class="form-box center">
                            <input type='hidden' name='csrfmiddlewaretoken' value='oj7UPyPT6snXJGi9l2u1nxJOuJliKgtpGZu4yzEhXCEjrkJf0A48H4ieAt11hctm' />

								    <div class="input-field">
                                    <div class="input-field">
                                        <label for="id_Item_Name">Item:</label><input id="id_Item_Name" maxlength="100" name="Item_Name" type="text" required />
                                    </div>
                                    </div>

								    <div class="input-field">
                                    <div class="input-field">
                                        <label for="id_Description">Description:</label><textarea cols="40" id="id_Description" maxlength="500" name="Description" rows="10" required></textarea>
                                    </div>
                                    </div>

								    <div class="input-field">
                                    <div class="input-field">
                                        <label for="id_Found_on">Found On:</label><input id="id_Found_on" maxlength="200" name="Found_on" type="text" required />
                                    </div>
                                    </div>


								    <div class="input-field">
                                    <label for="id_Item_Image">Insert an Image:
                                    <div class="input-field" id="choose-file">Choose:
                                        <input id="id_Item_Image" name="Item_Image" type="file" e />
                                    </div>
                                    </label>
                                    </div>

                            <div class="input-field">
							<input class="center" type="submit" name="submit_btn" value="Submit">
							</div><br>
							</div><br></div>
				</div>
			</div>
</form>

    <script>
    $('select').material_select();
    $('')
    </script>

{% endblock %}

Dashboard/templates/lostfound/reportlost.html
{% extends 'lostfound/base.html' %}

{% block title %} Found {% endblock %}

{% block css%}
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'terashare/upload.css' %}">
{% endblock %}
{% block titl %}
    Report Found
{% endblock %}
{% block body %}

<form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="container">
	  		<div class="row">
	  			<div class="container">
	  				<div class="row">
						<div class="form-box center">
                            <div class="input-field">
                                    <div class="input-field">
                                        <label for="id_Item_Name">Item:</label><input id="id_Item_Name" maxlength="100" name="Item_Name" type="text" required />
                                    </div>
                                    </div>

								    <div class="input-field">
                                    <div class="input-field">
                                        <label for="id_Description">Description:</label><textarea cols="40" id="id_Description" maxlength="500" name="Description" rows="10" required></textarea>
                                    </div>
                                    </div>

								    <div class="input-field">
                                    <div class="input-field">
                                        <label for="id_Last_Seen">Last Seen On:</label><input id="id_Last_Seen" maxlength="200" name="Last_Seen" type="text" required />
                                    </div>
                                    </div>


								    <div class="input-field">
                                    <label for="id_Item_Image">Insert an Image:
                                    <div class="input-field" id="choose-file">Choose:
                                        <input id="id_Item_Image" name="Item_Image" type="file" e />
                                    </div>
                                    </label>
                                    </div>
                            <div class="input-field">
							<input class="center" type="submit" name="submit_btn" value="Submit">
							</div><br>
                                <div class="right"><a href='#'><i class="material-icons" style="color: white;">arrow_forward</i></a></div></div>
                    </div>
				</div>
			</div>
</form>

    <script>
    $('select').material_select();
    $('')
    </script>

{% endblock %}